version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservation-system
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "35432:5432"
volumes:
  postgres:
