import { Carousel } from "@mantine/carousel";
import { Button, Container, Grid, Title, rem } from "@mantine/core";
import Autoplay from "embla-carousel-autoplay";
import Head from "next/head";
import { ReactElement, useRef } from "react";

import Link from "next/link";
import Card from "~/components/Card/Card";
import EmptyListHandler from "~/components/DataHandling/EmptyListHandler/EmptyListHandler";
import LoadingHandler from "~/components/DataHandling/LoadingHandler/LoadingHandler";
import Layout from "~/components/Layout/Layout";
import MatchPreview from "~/features/Match/MatchPreview/MatchPreview";
import { api } from "~/utils/api";
import * as _app from "./_app";

const data = [
  {
    image:
      "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Best forests to visit in North America",
    category: "nature",
  },
  {
    image:
      "https://images.unsplash.com/photo-1559494007-9f5847c49d94?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Hawaii beaches review: better than you think",
    category: "beach",
  },
  {
    image:
      "https://images.unsplash.com/photo-1608481337062-4093bf3ed404?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Mountains at night: 12 best locations to enjoy the view",
    category: "nature",
  },
  {
    image:
      "https://images.unsplash.com/photo-1507272931001-fc06c17e4f43?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Aurora in Norway: when to visit for best experience",
    category: "nature",
  },
  {
    image:
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Best places to visit this winter",
    category: "tourism",
  },
  {
    image:
      "https://images.unsplash.com/photo-1582721478779-0ae163c05a60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
    title: "Active volcanos reviews: travel at your own risk",
    category: "nature",
  },
];

const Home: _app.NextPageWithLayout = () => {
  const autoplay = useRef(Autoplay({ delay: 5000 }));
  const slides = data.map((item) => (
    <Carousel.Slide key={item.title}>
      <Card {...item} />
    </Carousel.Slide>
  ));

  const testData = api.test.findTestData.useQuery();

  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container mt="lg" size="lg">
          <Carousel
            slideSize={{ base: "100%" }}
            slideGap={{ base: rem(2) }}
            align="start"
            slidesToScroll={1}
            withIndicators
            plugins={[autoplay.current]}
            onMouseEnter={autoplay.current.stop}
            onMouseLeave={autoplay.current.reset}
            mb="xl"
          >
            {slides}
          </Carousel>

          <Grid mb="xl">
            <Grid.Col span={{ base: 12, md: 8 }}>
              <Title order={3}>Upcoming Matches</Title>
              <LoadingHandler status={testData.status}>
                <>
                  {testData.data && (
                    <EmptyListHandler length={testData.data.length}>
                      {testData.data.map(({ match, division, awayTeam, homeTeam, stadium }) => (
                        <MatchPreview
                          key={match.id}
                          match={match}
                          division={division}
                          awayTeam={awayTeam}
                          homeTeam={homeTeam}
                          stadium={stadium}
                        />
                      ))}
                    </EmptyListHandler>
                  )}
                </>
              </LoadingHandler>
              <Link href="/matches">
                <Button variant="default">View all Matches</Button>
              </Link>
            </Grid.Col>
          </Grid>
        </Container>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getStaticProps = async (context: any) => ({
  props: {
    messages: (await import(`src/lang/${context.locale}.json`)).default,
  },
});

export default Home;
